development:
  adapter: postgresql
  encoding: unicode
  database: supp_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: supp_test
  pool: 5
  username:
  password:
